#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"
mkdir -p logs

PIPE_TAG="${PIPE_TAG:-td3_mpcclone_nofuel_$(date +%Y%m%d_%H%M%S)}"
PARTITION="${PARTITION:-debug}"
TIME_LIMIT="${TIME_LIMIT:-12:00:00}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
MEM_GB="${MEM_GB:-40G}"

FIXED_INIT_PROFILE="${FIXED_INIT_PROFILE:-offset_ref}"
TRAIN_JITTER_POS="${TRAIN_JITTER_POS:-0.0}"
TRAIN_JITTER_VEL="${TRAIN_JITTER_VEL:-0.0}"
TRAIN_JITTER_TRIES="${TRAIN_JITTER_TRIES:-1}"
MPC_DATASET_SETUPS="${MPC_DATASET_SETUPS:-1}"
MPC_MAX_STEPS="${MPC_MAX_STEPS:-500}"
MPC_REPLAN_EVERY="${MPC_REPLAN_EVERY:-1}"
MPC_HORIZON="${MPC_HORIZON:-60}"
MPC_ITERS="${MPC_ITERS:-20}"
MPC_MODEL_SUBSTEPS="${MPC_MODEL_SUBSTEPS:-3}"
TD3_TOTAL_ENV_STEPS="${TD3_TOTAL_ENV_STEPS:-220000}"
TD3_PREFILL_MAX_SAMPLES="${TD3_PREFILL_MAX_SAMPLES:-120000}"
TD3_EXPL_NOISE_START="${TD3_EXPL_NOISE_START:-0.03}"
TD3_EXPL_NOISE_END="${TD3_EXPL_NOISE_END:-0.005}"
TD3_EXPL_DECAY_STEPS="${TD3_EXPL_DECAY_STEPS:-100000}"
BC_LR="${BC_LR:-1e-3}"
TD3_ACTOR_LR="${TD3_ACTOR_LR:-1e-3}"
TD3_CRITIC_LR="${TD3_CRITIC_LR:-1e-3}"

echo "Submitting TD3 MPC-clone NO-FUEL-PENALTY pipeline"
echo "PIPE_TAG=$PIPE_TAG"
echo "PARTITION=$PARTITION TIME=$TIME_LIMIT CPU=$CPUS_PER_TASK MEM=$MEM_GB"
echo "FIXED_INIT_PROFILE=$FIXED_INIT_PROFILE TRAIN_JITTER_POS=$TRAIN_JITTER_POS TRAIN_JITTER_VEL=$TRAIN_JITTER_VEL"
echo "BC_LR=$BC_LR TD3_ACTOR_LR=$TD3_ACTOR_LR TD3_CRITIC_LR=$TD3_CRITIC_LR"
echo "TD3_W_FUEL=0.0 TD3_W_NEAR_COLLISION=0.0 TD3_W_ESCAPE=0.0"

JOB_ID=$(
  sbatch --parsable \
    --partition="$PARTITION" \
    --time="$TIME_LIMIT" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEM_GB" \
    --export=ALL,PIPE_TAG="$PIPE_TAG",FIXED_INIT_PROFILE="$FIXED_INIT_PROFILE",TRAIN_JITTER_POS="$TRAIN_JITTER_POS",TRAIN_JITTER_VEL="$TRAIN_JITTER_VEL",TRAIN_JITTER_TRIES="$TRAIN_JITTER_TRIES",MPC_DATASET_SETUPS="$MPC_DATASET_SETUPS",MPC_MAX_STEPS="$MPC_MAX_STEPS",MPC_REPLAN_EVERY="$MPC_REPLAN_EVERY",MPC_HORIZON="$MPC_HORIZON",MPC_ITERS="$MPC_ITERS",MPC_MODEL_SUBSTEPS="$MPC_MODEL_SUBSTEPS",TD3_TOTAL_ENV_STEPS="$TD3_TOTAL_ENV_STEPS",TD3_PREFILL_MAX_SAMPLES="$TD3_PREFILL_MAX_SAMPLES",TD3_EXPL_NOISE_START="$TD3_EXPL_NOISE_START",TD3_EXPL_NOISE_END="$TD3_EXPL_NOISE_END",TD3_EXPL_DECAY_STEPS="$TD3_EXPL_DECAY_STEPS",BC_LR="$BC_LR",TD3_ACTOR_LR="$TD3_ACTOR_LR",TD3_CRITIC_LR="$TD3_CRITIC_LR",TD3_W_FUEL=0.0,TD3_W_NEAR_COLLISION=0.0,TD3_W_ESCAPE=0.0 \
    sbatch_td3_mpc_clone_pipeline.sh
)

echo "JOB_ID=$JOB_ID"
echo "PIPE_TAG=$PIPE_TAG"
echo "Track:"
echo "  squeue -j $JOB_ID"
echo "Logs:"
echo "  logs/csci1470_td3_mpcclone_${JOB_ID}.out"
echo "  logs/csci1470_td3_mpcclone_${JOB_ID}.err"
